name = "ClassicalTestTheory"
uuid = "e40851f3-a233-49cf-835f-c29ce827671a"
authors = ["Philipp Gewessler <p.gewessler@gmx.at> and constributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
